services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_postgres_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test # Change this!
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      # This line now correctly points to your new 'init-db' directory
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
